bookstore
MaVaYuran/bookstore pull request #1
Opened 2024-11-05 15:56 UTC by MaVaYuran

2024-11-05 17:05 UTC, Alexmansar requested changes
@MaVaYuran 
please, check comments

2024-11-05 17:05 UTC, Alexmansar commented on src/main/java/by/mariayuran/BookStore.java
> +    }
why inside this merhod we also call 
createOrderList(newOrder);?

2024-11-05 17:05 UTC, Alexmansar commented on src/main/java/by/mariayuran/BookStore.java
> +        Collections.sort(sortedOrders, comparator);
👍

2024-11-05 17:05 UTC, Alexmansar commented on src/main/java/by/mariayuran/Order.java
> +        books = new ArrayList<>();
in each call ypu ypu new List. make books = new ArrayList<>(); onve on the field level

2024-11-05 17:05 UTC, Alexmansar commented on src/main/java/by/mariayuran/BookStore.java
> +        int bookId = random.nextInt(books.size() - 1);
toreBooks.size(); ?

2024-11-06 20:16 UTC, MaVaYuran commented on src/main/java/by/mariayuran/BookStore.java
> +        int bookId = random.nextInt(books.size() - 1);
I dont understand

2024-11-07 11:15 UTC, Alexmansar commented on src/main/java/by/mariayuran/BookStore.java
> +        int bookId = random.nextInt(books.size() - 1);
storeBooks.size();

2024-11-07 11:16 UTC, Alexmansar commented on src/main/java/by/mariayuran/BookStore.java
> +        int bookId = random.nextInt(books.size() - 1);
You use it as paaramert. but in this vlass you have this field as well. or not?

2024-11-07 12:01 UTC, Alexmansar approved these changes
@MaVaYuran 
Please, merge it

2024-11-07 12:56 UTC, merged