changed loops for lambda
MaVaYuran/bookstore pull request #7
Opened 2024-11-12 15:32 UTC by MaVaYuran

2024-11-12 16:43 UTC, Alexmansar requested changes
@MaVaYuran 
Hi) please, fix the comment. and add logic to work with files

2024-11-12 16:43 UTC, Alexmansar commented on src/main/java/by/mariayuran/Order.java
> +                .forEach(i -> this.addBook(getAnyBook(books)));
what is i?

2024-11-12 17:36 UTC, Alexmansar commented
@MaVaYuran I add review, why you ask again without any updates?

2024-11-12 17:36 UTC, MaVaYuran commented on src/main/java/by/mariayuran/Order.java
> +                .forEach(i -> this.addBook(getAnyBook(books)));
this is method for entering number of books in order from console

2024-11-13 11:10 UTC, Alexmansar requested changes
@MaVaYuran Hi)) good job)) please, add tests fr new methods as well))

2024-11-17 07:57 UTC, Alexmansar commented on src/main/java/by/mariayuran/Order.java
> +                .forEach(i -> this.addBook(getAnyBook(books)));
i. use name

2024-11-18 10:38 UTC, Alexmansar requested changes

2024-11-18 10:38 UTC, Alexmansar commented on src/main/java/by/mariayuran/Main.java
> +//        ObjectMapper objectMapper = null;
remove please

2024-11-18 10:38 UTC, Alexmansar commented on src/main/java/by/mariayuran/Order.java
> +//    }
and here

2024-11-18 10:38 UTC, Alexmansar commented on src/test/java/by/mariayuran/OrderTest.java
> +//        bookStore = new BookStore(libraryRepository);
same

2024-11-18 10:38 UTC, Alexmansar commented on src/main/java/by/mariayuran/library/LibraryRepositoryImpl.java
> +        String filePath = "src/main/resources/orders.json";
In lines 29 and 42, we use different approaches. Can we use the same one?

2024-11-18 13:30 UTC, MaVaYuran commented on src/main/java/by/mariayuran/library/LibraryRepositoryImpl.java
> +        String filePath = "src/main/resources/orders.json";
not sure, because there are different filepath

2024-11-18 14:16 UTC, Alexmansar commented on src/main/java/by/mariayuran/library/LibraryRepositoryImpl.java
> +        String filePath = "src/main/resources/orders.json";
try (InputStream inputStream = getClass().getClassLoader().getResourceAsStream(filePath)) {
can we use in  writeOrderToJson?

2024-12-02 19:10 UTC, merged